version: "3.6"
services:
  database:
    image: mysql:5.7
    container_name: database-container
    restart: always
    ports: # 映射端口
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456" # 初始化root用户密码
      MYSQL_DATABASE: "bus_real_time" # 初始化数据库
      TZ: "Asia/Shanghai" # 设置时区
    volumes:
      - "~/docker-data/mysql/5.7/db:/var/lib/mysql"
      - "~/docker-data/mysql/5.7/logs:/var/log/mysql:rw"      
      - "~/docker-data/mysql/5.7/initdb.d:/docker-entrypoint-initdb.d:ro"