version: "3.6"
services:
  mysql8:
    image: mysql
    container_name: mysql8-container
    restart: always
    ports: # 映射端口
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD='123456' # 初始化root用户密码
      - MYSQL_DATABASE=bus_real_time # 初始化数据库
      - TZ=Asia/Shanghai # 设置时区
    volumes:
      - ~/Users/tapas/docker-data/mysql:/var/lib/mysql # 数据持久化 mac设置
      # - /data/mysql:/var/lib/mysql
    # 设置mysql字符串集方式和 collation排序字段方式
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
